# Generated by Django 3.2 on 2021-11-09 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mirnaset',
            name='mirna_id',
            field=models.ManyToManyField(to='analysis.Mirna'),
        ),
        migrations.AddField(
            model_name='mirnaset',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mirna',
            name='gene_target',
            field=models.ManyToManyField(through='analysis.Target', to='analysis.Gene'),
        ),
        migrations.AddField(
            model_name='geneset',
            name='genes_id',
            field=models.ManyToManyField(to='analysis.Gene'),
        ),
        migrations.AddField(
            model_name='geneset',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gene',
            name='synthetic_lethal',
            field=models.ManyToManyField(blank=True, related_name='_analysis_gene_synthetic_lethal_+', to='analysis.Gene'),
        ),
        migrations.AddField(
            model_name='file',
            name='workflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.workflow'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['gene_id', 'mirna_id'], name='analysis_ta_gene_id_fc44cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('gene_id', 'mirna_id')},
        ),
        migrations.AddIndex(
            model_name='mirna',
            index=models.Index(fields=['mature_id'], name='analysis_mi_mature__d1ddaf_idx'),
        ),
    ]
