# Generated by Django 3.2 on 2021-11-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneset',
            name='description',
            field=models.TextField(max_length=900000, null=True),
        ),
    ]
