# Generated by Django 3.2 on 2021-12-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_geneset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='logs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
