# Generated by Django 3.2 on 2021-12-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_workflow_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField()),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.workflow')),
            ],
        ),
    ]
