# Generated by Django 3.2 on 2021-12-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_rename_prediction_tools_prediction_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction_tool',
            name='doi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prediction_tool',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prediction_tool',
            name='pmid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prediction_tool',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prediction_tool',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
